### ISSUE TITLE
Unable to Run TTS Example

### ISSUE THREAD

**Issue by my-yy** [yangdongchao/UniAudio#10]
Hi, thank you for your fantastic work. 
I'm trying to run the TTS Example.  When I execute the command `bash run.sh --stage 2 --stop_stage 4`, I encounter the following errors:

```
split the data for 1 GPUs
run.sh: line 86: utils/split_scp.pl: Permission denied
Traceback (most recent call last):
  File "data_scripts/filter_scp.py", line 13, in <module>
    for line in open(ref_f, encoding='utf-8'):
FileNotFoundError: [Errno 2] No such file or directory: 'data/val/1splits/wav.1.scp'
run.sh: line 86: utils/split_scp.pl: Permission denied
Traceback (most recent call last):
  File "data_scripts/filter_scp.py", line 13, in <module>
    for line in open(ref_f, encoding='utf-8'):
FileNotFoundError: [Errno 2] No such file or directory: 'data/train/1splits/wav.1.scp'
Prepare text and audio sequence
prepare val ... 
run.sh: line 109: utils/run.pl: Permission denied
```

I didn't  modify the contents in `UniAudio/egs/TTS/data`.

Could you please confirm if this issue is related to not specifying the local location of the LibriTTS dataset? 
If so, how and where should I configure it?
Thanks!

**Comment by yangdongchao** [comment]
> Hi, thank you for your fantastic work. I'm trying to run the TTS Example. When I execute the command `bash run.sh --stage 2 --stop_stage 4`, I encounter the following errors:
> 
> ```
> split the data for 1 GPUs
> run.sh: line 86: utils/split_scp.pl: Permission denied
> Traceback (most recent call last):
>   File "data_scripts/filter_scp.py", line 13, in <module>
>     for line in open(ref_f, encoding='utf-8'):
> FileNotFoundError: [Errno 2] No such file or directory: 'data/val/1splits/wav.1.scp'
> run.sh: line 86: utils/split_scp.pl: Permission denied
> Traceback (most recent call last):
>   File "data_scripts/filter_scp.py", line 13, in <module>
>     for line in open(ref_f, encoding='utf-8'):
> FileNotFoundError: [Errno 2] No such file or directory: 'data/train/1splits/wav.1.scp'
> Prepare text and audio sequence
> prepare val ... 
> run.sh: line 109: utils/run.pl: Permission denied
> ```
> 
> I didn't modify the contents in `UniAudio/egs/TTS/data`.
> 
> Could you please confirm if this issue is related to not specifying the local location of the LibriTTS dataset? If so, how and where should I configure it? Thanks!

try to use ```sudo chmod 777 utils/run.pl```

**Comment by my-yy** [comment]
Thanks! It works!
