### ISSUE TITLE
Codec Training and Data Config

### ISSUE THREAD

**Issue by BismarckBamfo** [yangdongchao/UniAudio#3]
It looks like these files in the codec config are missing

########### training and data config ###########

training_file: "train_valid_lists/train.lst"
validation_file: "train_valid_lists/valid_256.lst"

**Comment by yangdongchao** [comment]
> It looks like these files in the codec config are missing
> 
> ########### training and data config ###########
> 
> training_file: "train_valid_lists/train.lst" validation_file: "train_valid_lists/valid_256.lst"

You should prepare it by ourself, each line is a audio path:
audio_path/1.wav
audio_path/2.wav
