### ISSUE TITLE
Do you have a plan to release pre-trained model weights ?

### ISSUE THREAD

**Issue by ZhihaoDU** [yangdongchao/UniAudio#7]
Hi, nice work and fancy results. I wonder do you have a plan to release pre-trained model weights ? Thus, we can test some cases by ourself. Thanks.

**Comment by yangdongchao** [comment]
> +1, could you please also share your codec model? As the codec model is the foundation model. tks

The codec model has been released, please refer to readme.md found it.

**Comment by yangdongchao** [comment]
> Hi, nice work and fancy results. I wonder do you have a plan to release pre-trained model weights ? Thus, we can test some cases by ourself. Thanks.

We have no plan to share the checkpoint now. Due to the potential misuse.

**Comment by ZhihaoDU** [comment]
> > +1, could you please also share your codec model? As the codec model is the foundation model. tks
> 
> The codec model has been released, please refer to readme.md found it.

I didn't find the released codec model in the readme.md files of both the repo and codec dir. where is it ?

**Comment by cantabile-kwok** [comment]
> > > +1, could you please also share your codec model? As the codec model is the foundation model. tks
> > 
> > 
> > The codec model has been released, please refer to readme.md found it.
> 
> I didn't find the released codec model in the readme.md files of both the repo and codec dir. where is it ?

I found it is hidden in the `UniAudio/download.sh`. The universal_model.pth seems to be the codec model 😄
